apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
  namespace: mvnwork
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: 311301640590.dkr.ecr.us-east-2.amazonaws.com/mvncontainer:9
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080       
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
  namespace: mvnwork
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: springboot

---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
  namespace: mvnwork
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
...		 
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: mvnwork
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo