apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.150.0.4
    path: "/nfs_backup/nfs_backup4/"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.150.0.4
    path: "/nfs_backup/nfs_backup4/"
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.150.0.4
    path: "/nfs_backup/nfs_backup4/"

