---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: springbootpath
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

