apiVersion: v1
kind: ReplicationController
metadata:
  name: springbootrc
  namespace: springbootpath
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo:latest
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080

